### ISSUE TITLE
坑爹，最基础的单元测试都通不过，怎么能开源，敬业一点好不好

### ISSUE THREAD

**Issue by zonghaishang** [remoting/dubbox#3]
version2.8.4

**Comment by wudepengegova** [comment]
问题本身是存在，但说话的方式不敢苟同；
等你有开源作品出来，你再站在这个高度来指点江山

**Comment by zonghaishang** [comment]
很抱歉我说话的方式，没有批评的意思，我觉得无私分享是美的，做技术还是希望能有一种精益求精的精神。

在 2018年3月30日，17:14，wudepengegova <notifications@github.com<mailto:notifications@github.com>> 写道：


问题本身是存在，但说话的方式不敢苟同；
等你有开源作品出来，你再站在这个高度来指点江山
